### ISSUE TITLE
No hint path defined for [sitemap].

### ISSUE THREAD

**Issue by oillescas** [dwightwatson/sitemap#10]
When I generated a sitemaps with Laravel 5 gives me the following error,

    No hint path defined for [sitemap].

I have solved adding in SitemapServiceProvider-> boot the next line.

    $this->loadViewsFrom(__DIR__.'/../../views', 'sitemap');

a greeting

sorry for my English

**Comment by dwightwatson** [comment]
Hey, if this fixes it on Laravel 5 please feel free to make a PR and I'll pull it in. Haven't had a chance to play with Laravel 5 just yet.
