### ISSUE TITLE
Add method to clear current sitemap

### ISSUE THREAD

**Issue by Maykonn** [dwightwatson/sitemap#13]
When creating sitemaps to a index inside a loop, chunking to create a index after, Sitemap:addSitemap() method are appending results from previous iteration. Example:

```
    $i=0;
    \Model::chunk(20, function ($results) use(&$i) {
        Sitemap::addSitemap('/sitemaps/' . $i.'.xml');

        foreach ($results as $result) {
            Sitemap::addTag('http://url-to-entity/' . $result->slug, $result->updated_at, 'weekly', '0.8');
        }

        \S3::putObject(Sitemap::xml());
        $i++;
    });
```

First file 1.xml is ok, but the second 2.xml, contents have contents from first and second. So, Sitemap::addSitemap() method must clear results when called to avoid this behaviour.
Or exists other method to clean results?

**Comment by dwightwatson** [comment]
I'm uncomfortable with `addSitemap()` clearing the tags by default, I don't think that's expected behaviour.

I've added the `clear()` method which will clear out all existing sitemaps and tags, as well as the `clearSitemaps()` and `clearTags()` methods in the latest release `2.0.6`.

**Comment by Maykonn** [comment]
To work to me, I just extends the Sitemap class to change the constructor method, because I don`t need cache inject. And to add the possibility to create a real instance of Sitemap? $Sitemap = new Sitemap();

To this instance I just addTags. After just render xml of index sitemap. Works.

**Comment by dwightwatson** [comment]
Yeah, maybe my approach of using a singleton here wasn't the best idea. Something I'll consider changing for a future version.

**Comment by Maykonn** [comment]
Is a good idea to create simple sitemaps. For most projects works fine. Most of the projects never uses more than 50k of entries in a single sitemap, thus is a good approach for it.

We just need to think about projects that need complex sitemaps, with lots of sitemaps to an sitemap index. See if the bellow approach can help you: 

```
// chunk Model loop...
    $Sitemap = Sitemap::newSitemap('/path/to/sitemap.xml'); // returns a new self instance; 
    $Sitemap->addTagToSitemap(/*same params of addTag*/); 

    // So, to append the new sitemap path to sitemap index:
    Sitemap::addSitemap($Sitemap->getPath());
// end of chunk.
```

It works!

**Comment by dwightwatson** [comment]
Yeah, in my setup I actually use different routes for different sitemaps so that a single request only produces one sitemap. You can still produce complex sitemaps, it's just a different workflow.

Also instead of subclassing the `Sitemap` class just to create one with ease you should be able to get an instance ready to go from the IoC container. If you're using Laravel 5 you could just call `$sitemap = app('Watson\Watson\Sitemap');` to get a fresh instance.

**Comment by Maykonn** [comment]
Yeah, I forgot! =D

I understand now you idea... is a route based sitemap. I had just one route to sitemap: GET /sitemaps/{type}. The type param is used by client apps, CRON job tha create sitemap to Google uses xml on type param, and client apps like Angular.js, or a PHP client application that need to create a view to show to users a sitemap on the screen, so can uses json to type param. 

Thanks!
