### ISSUE TITLE
Errors on Laravel 4

### ISSUE THREAD

**Issue by danboh** [dwightwatson/sitemap#14]
Hi, thank you for this package.

I just tried implementing this with Laravel 4.2 and getting a few errors:

1. Call to undefined method Watson\Sitemap\Sitemap::index() 
I was able to resolve this one by replacing Index() by renderSitemap() perhaps you should update your docs?

2. XML Parsing Error: XML or text declaration not at start of entity
It seems that the xml is being return with an extra space at the beginning.

**Comment by dwightwatson** [comment]
I've updated the docs to point you towards the `1.1` branch, where the docs are for that version of the package.

I can't replicate the extra space, I tried with a fresh copy of Laravel 4.2 and the package. You should double-check you haven't popped a space before the opening of a `<?php` tag somewhere in your code. If you can narrow down the issue or provide some replication of it I'll be happy to resolve it. :smile:

**Comment by danboh** [comment]
Hey, thanks for the quick response.

I have no idea why the extra space, but doesn't seem to be an issue for google when using your class to submit the sitemap. 

Thanks anyways.
