### ISSUE TITLE
More example

### ISSUE THREAD

**Issue by PatSpiegel** [dwightwatson/sitemap#15]
example for add 
Images: xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
Video: xmlns:video="http://www.google.com/schemas/sitemap-video/1.1"
Mobile: xmlns:mobile="http://www.google.com/schemas/sitemap-mobile/1.0"
News: xmlns:news="http://www.google.com/schemas/sitemap-news/0.9"

**Comment by dwightwatson** [comment]
I'm not sure what you're suggesting there, that I add these to the header of a sitemap? 

Could you explain what purpose they serve?
