### ISSUE TITLE
Multilingual

### ISSUE THREAD

**Issue by GregoryClaeyssens** [dwightwatson/sitemap#16]
Any ideas on how to achieve a multilingual sitemap?
Google has an article on how to do this [here](https://support.google.com/webmasters/answer/2620865?hl=en). But how can we achieve this with the package, or am I overlooking something obvious?

Thanks in advance

**Comment by dwightwatson** [comment]
Not with this package unfortunately, the base XML is a template. I'd happily accept a PR to add this feature, but it's not something I'm looking to implement I'm afraid.

**Comment by jonasvanderhaegen** [comment]
I managed to fix this, as last parameter you give an array with key your language and value whatever url. I'll make a pull request soon. ;)

**Comment by jonasvanderhaegen** [comment]
Made a pull request for this :) @dwightwatson @GregoryClaeyssens
