### ISSUE TITLE
Change frequency and priority not showing up

### ISSUE THREAD

**Issue by sanderjansma** [dwightwatson/sitemap#19]
Hi! 

Thanks for the awesome package. I only have one issue: I use the following to add a tag to a sitemap, as shown in the example:
Sitemap::addTag(url('/', $post->slug), $date, 'weekly', '0.8');

For some reason the frequency and priority aren't showing up in the sitemap, but only: 

<url>
<loc>site.com/post-url</loc>
<lastmod>2015-09-30T12:28:46+00:00</lastmod>
</url>

Any idea on how I can fix this so that they do show up in the sitemap?

**Comment by dwightwatson** [comment]
Ugh! Pushed out an update today - I think this could have broken it. Looking into it right away. Hold on.

**Comment by dwightwatson** [comment]
Fixed, pushed, tagged. This should be available through Composer in a little bit (version 2.0.8). Sorry about this, thanks for letting me know!

**Comment by sanderjansma** [comment]
Wow that was fast! Thanks for the fast response and fix!
