### ISSUE TITLE
Query strings cause Sitemap errors

### ISSUE THREAD

**Issue by adampatterson** [dwightwatson/sitemap#25]
I created a sitemap with a number of query strings ( inventory search ) and get errors once I add the second parameter to the URL.

**Example:** http://somesite.com/file.php?c=1&d=2&e=3

After some research, I think the URL should be http://somesite.com/file.php?c=1&amp;d=2&amp;e=3 

I created the URL using
```
route('search', [
    'make_name'  => $url->make_name,
    'model_name' => $url->model_name
])
```

I resolved the issue by wrapping route with htmlspecialchars()

I think that addTag should handle this automatically to prevent confusion.

**Comment by dwightwatson** [comment]
Your example URL is the correct and valid one. Query strings begin with a question mark, are delimited by ampersands and the key value pairs are separated by equals signs. The second URL you provided has escaped the ampersands which should only be done in HTML - hence the function's name `htmlspecialchars()`.

If you can provide more information about what is going wrong when visiting the URL then we can take a look at what is going wrong - but the URL generation looks to be working as expected.

**Comment by adampatterson** [comment]
The first example when loaded by sitemap validation tool gives me the following.

http://content.screencast.com/users/kbazinet/folders/Snagit/media/9a7f2ada-072f-4dcb-8f26-e631f8787c09/04.04.2016-13.58.png

When I convert the ampersands to &amp; and recheck validation It passes.

Here is the source without using htmlspecialcheracters()  http://ga.p53.ca/sitemap/search

![image](https://cloud.githubusercontent.com/assets/31537/14269365/0bc8a206-faa1-11e5-8c63-0dfc4e6ef86e.png)

This is a staging site so issue won't be there for that long.

Thanks!

**Comment by dwightwatson** [comment]
Oh right - I get you. Sorry, I clearly wasn't thinking right this morning.

it looks like there's a second argument to `htmlspecialchars()` that is specific to XML.

I'll wrap the URLs in the sitemaps in the function to escape them and push it to `master`. If that solves the issue then I can push it out as a tagged release.

**Comment by adampatterson** [comment]
Cool, thanks!

I had a quick look at the code but am not familiar with what instance of does otherwise I would have made a pull request for you.

Thanks again!

**Comment by dwightwatson** [comment]
All good - thanks for reporting the issue. I just had a quick play with the fix and this looks to be working as expected so I might just tag it and push it out. Let me know if you run into any more issues!
