### ISSUE TITLE
Suggestion: Public function to check if a cached sitemap exists

### ISSUE THREAD

**Issue by bridgeport** [dwightwatson/sitemap#30]
First, thanks for the package. Since cache support exists, wouldn't it make sense for there to be an available function to test if the cache exists before unnecessarily adding tags?

For instance, if a sitemap requires querying the database and hundreds or thousands of tags being added, only to be discarded because a cached sitemap already exists, then that processing was ultimately unnecessary. It looks as though the `render()` function does such a check with the `getCachedView()` method. If that method were public instead of protected it could technically be used as such:

```php
class SitemapController extends Controller
{
    public function index()
    {
        if (!\Sitemap::getCachedView()) {
            \Sitemap::addTag(url('/'), null, null, '1.0');
            // A bunch of other expensive processing (e.g., database queries)
        }
        return \Sitemap::render();
    }
```

But that's returning the view. It would be nice to have a function that returned a boolean value.

Thanks.

**Comment by dwightwatson** [comment]
Good call. I've just pushed an update with `hasCachedView()` and tagged it `2.0.14`. It should be available through Composer in a couple of minutes. Hope this helps!

**Comment by bridgeport** [comment]
Great stuff. Thanks @dwightwatson
