### ISSUE TITLE
Sitemap or Sitemap index file doesn't properly declare the namespace.

### ISSUE THREAD

**Issue by werring** [dwightwatson/sitemap#32]
After submitting the generated sitemap google does index all pages but does return this error:

`Your Sitemap or Sitemap index file doesn't properly declare the namespace. Expected: http://www.w3.org/1999/xhtml Found: http://www.w3.org/TR/xhtml11/xhtml11_schema.html`

Is there a specific reason that `http://www.w3.org/TR/xhtml11/xhtml11_schema.html` was picked over `http://www.w3.org/1999/xhtml`

**Comment by dwightwatson** [comment]
Not that I can think of. Never seen this issue before. I think we can probably get rid of all the additional schemas defined in the sitemap.
