### ISSUE TITLE
Getting - error on line 2 at column 6: XML declaration allowed only at the start of the document

### ISSUE THREAD

**Issue by ivandoric** [dwightwatson/sitemap#33]
I'm getting the above mentioned error. And when I do "View source" xml is rendered but it seems that the first line is empty. This is my controller:

```
public function accommodation(){
        $accommodations = Accommodation::all();

        foreach ($accommodations as $accommodation) {
            Sitemap::addTag(route('accommodationitem', $accommodation), $accommodation->updated_at, 'daily', '0.8');
        }

        return Sitemap::render();
    }
```

Where is that empty line coming from?

**Comment by dwightwatson** [comment]
When I've seen this before, it's because one of the PHP files in the app had whitespace before the opening PHP tag. Double check you haven't done that to any of your apps files.

**Comment by ivandoric** [comment]
Thanks for the quick response, that was it, and it was totally unrelated file that was the problem.

**Comment by dwightwatson** [comment]
All good, glad you're back up and running!

**Comment by dakshhmehta** [comment]
This saved my day!

Thanks dear!
