### ISSUE TITLE
Priority should be after lastmod and changefreq

### ISSUE THREAD

**Issue by cameronhaddad** [dwightwatson/sitemap#35]
After running your output through a sitemap validator (http://tools.seochat.com/tools/site-validator/) it fails as the priority tag is in the wrong space.

Also it would be nice to better tab your XML output (as the IF) tags add extra indenting to the sub tags.

**Comment by dwightwatson** [comment]
I've added those changes to `master`, if you could try them out and let me know if they work better for you that would be great. Then I can tag it as a new release.

**Comment by cameronhaddad** [comment]
Im on laravel 4 so im using v1.1.  But this change looks good.  I did the equivalent changes to 1.1 and works.

Thanks for the quick response.

**Comment by dwightwatson** [comment]
No worries. Feel free to make a PR to the 1.1 branch if you want that change upstream too.
