### ISSUE TITLE
How to make big site maps with over 1 million urls

### ISSUE THREAD

**Issue by deep88** [dwightwatson/sitemap#42]
i want to create sitemap for a website that has more than 1 million pages.. i want to know how can i create that without effecting the server health. and without getting server timeout error..

**Comment by dwightwatson** [comment]
You will need to create a sitemap index that links to additional site maps. There are instructions on how to do this dynamically in the readme. You can use caching to reduce impact on the server and you can also adjust the server timeout as well.

**Comment by deep88** [comment]
is it possible to append urls to existing sitemap ?

**Comment by dwightwatson** [comment]
Yes, if the sitemap was created through this library. Read through the docs, the whole thing is dynamic.

**Comment by deep88** [comment]
thank you
