### ISSUE TITLE
Can`t install

### ISSUE THREAD

**Issue by Valonix** [dwightwatson/sitemap#43]
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing watson/sitemap (2.0.18)

Installation failed, reverting ./composer.json to its original content.
The following exception is caused by a lack of memory or swap, or not having swap configured
Check https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors for details

PHP Warning:  proc_open(): fork failed - Cannot allocate memory in phar:///usr/local/bin/composer/vendor/symfony/console/Application.php on line 957

Warning: proc_open(): fork failed - Cannot allocate memory in phar:///usr/local/bin/composer/vendor/symfony/console/Application.php on line 957
                                                     
  [ErrorException]                                   
  proc_open(): fork failed - Cannot allocate memory

**Comment by dwightwatson** [comment]
That's an issue with your PHP/Composer setup. It can't allocate the memory necessary to install a package. Read the Composer troubleshooting guide linked in the error output.
