### ISSUE TITLE
Generating video sitemaps

### ISSUE THREAD

**Issue by mateoprifti** [dwightwatson/sitemap#49]
Greetings,
First off thank you for this great package.

Question: How would someone be able to generate video sitemaps in xml?
such as here
http://www.whitehatmedia.com/blog/how-create-video-sitemap

thank you.

**Comment by dwightwatson** [comment]
Hey, thank you. Haven't heard of video sitemaps before, but having had a look at your link there I don't think this is something this package supports at the moment. Happy to accept a PR that adds this functionality but unfortunately it's not going to be something I'll have time to work on soon.

**Comment by dwightwatson** [comment]
This should be sorted now thanks to @hthabet.
