### ISSUE TITLE
Examples for View

### ISSUE THREAD

**Issue by mike23v** [dwightwatson/sitemap#52]
I just want to ask if you do have an examples for the view using the sitemap package.

**Comment by dwightwatson** [comment]
I'm not sure what you mean here...

Sitemap does all the rendering under the hood so you just return `Sitemap::render()` rather than a view file.

**Comment by mike23v** [comment]
I'm a little bit confused on this part, 
  foreach ($posts as $post) {
             Sitemap::addTag(route('posts.show', $post), $post->updated_at, 'daily', '0.8');
        }

Are you saying that I have to create a view for posts.show? I'm just new in creating an sitemap.xml

**Comment by dwightwatson** [comment]
That's an example with a Post model. You need to tell `addTag` how to link to the model. `route('posts.show')` uses Laravel's router to build a link to the post. As an example, it might end up passing arguments like this...

```php
Sitemap::addTag('/posts/1', '2017-01-01 00:00:00', 'daily', '0.8');
```

The first argument is just a link to the resource you want in your sitemap. Please let me know if this doesn't help.

**Comment by mike23v** [comment]
@dwightwatson Thanks for that clarification. One last thing, can the package produce a sitemap.xml file?

**Comment by dwightwatson** [comment]
You can call the `xml()` method instead of `render()` and you'll get the XML sitemap, but you'll need to save that to a file yourself if you want to serve it straight off the disk.

**Comment by mike23v** [comment]
I got a 10,000 records and it cant load all in a page. It says "504 Gateway timeout". I can only load up to 400 records that's why I'm looking a way to save directly to a file "sitemap.xml"

**Comment by dwightwatson** [comment]
Not sure what to tell you - I haven't run into that issue yet. If you need to write your sitemap out to a file then [spatie/laravel-sitemap](https://github.com/spatie/laravel-sitemap) might be a better fit for your needs.
