### ISSUE TITLE
feed invalid

### ISSUE THREAD

**Issue by pbgswd** [dwightwatson/sitemap#55]
Feed: https://theinternationalforecaster.com/sitemaps/posts

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Ftheinternationalforecaster.com%2Fsitemaps%2Fposts

line 1, column 38: Undefined root element: urlset

Not sure why it is not validating. I will keep looking at it and try and figure it out.

**Comment by dwightwatson** [comment]
Hey, out of town for the weekend but just had a quick look into this one. [Came across this discussion on a Google board](https://productforums.google.com/forum/#!topic/news/-cfFdRd2F0w) which points out that you can't use an RSS feed validator on a sitemap - they can both be XML but they're fundamentally different. In other words, I wouldn't be concerned that the W3 feed validator doesn't like the output of your sitemap.

Please let me know if you think this is wrong and I'm happy to dig in further, but I think you should be good to go for now.

**Comment by pbgswd** [comment]
No need to dig further, thank you.
