### ISSUE TITLE
Outdated Readme

### ISSUE THREAD

**Issue by AdnanHussainTurki** [dwightwatson/sitemap#71]
I have been using the repo. But as per the repo the addTags and other functions are not working.

**Comment by dwightwatson** [comment]
There's no method called `addTags` in the readme?

There's a method call` addTag` which is clearly defined [here](https://github.com/dwightwatson/sitemap/blob/master/src/Watson/Sitemap/Sitemap.php#L117-L124).

If you're running into errors please provide example code that can be used to reproduce the error.
