### ISSUE TITLE
File is not generating

### ISSUE THREAD

**Issue by theamanjs** [dwightwatson/sitemap#72]
I've tried using `Sitemap::xml()` and it displays the file as plain text on the route which I specified. When I used `Sitemap::render()` it shows me the required output but I'm not able to export the file. Please confirm that this member function exports the XML file, right? If no, can you please help me to get the XML file on a specific location and specific name?

**Comment by dwightwatson** [comment]
`Sitemap::xml()` returns the raw XML text. If you want to return it an XML response you would need to send the correct headers so the browser knows what it's dealing with.

```php
return response()->make(Sitemap::xml(), 200, ['Content-Type' => 'application/xml']);
```
