### ISSUE TITLE
Reusing the existing tags in Sitemap Controller

### ISSUE THREAD

**Issue by theamanjs** [dwightwatson/sitemap#73]
If my sitemap is generating from two different constraints like
`https://example.com/{brand}`
`https://example.com/{brand}/{location}`
For this, I need to run the loop twice, once for `brand` only and once for `brand/location`, and the second time the loop will be heavier due to `brands` X `locations`. Is there any way to append the `location` with the older `brand` link?

**Comment by dwightwatson** [comment]
Without knowing how your app works I don’t really know. You can always cache query results if you want to reuse them between different requests, but the sitemap package doesn’t contain any support for this out of the box.

**Comment by theamanjs** [comment]
Thank you for this super-fast help :+1:
